"""add zipcode to users

Revision ID: 830623d434f7
Revises: bbd6d60d87eb
Create Date: 2018-05-09 21:41:04.613778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830623d434f7'
down_revision = 'bbd6d60d87eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zipcode')
    # ### end Alembic commands ###
